# Generated by Django 2.1 on 2020-02-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_url',
            new_name='url',
        ),
    ]
