# Generated by Django 2.1 on 2020-03-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bookmarks_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='date_bookmarked',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='date_tagged',
            field=models.DateTimeField(),
        ),
    ]
