# Generated by Django 2.1 on 2020-03-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200306_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='date_bookmarked',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='date_tagged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
