# Generated by Django 2.1 on 2020-03-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200315_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_url',
            field=models.URLField(default='blank', max_length=2000),
        ),
    ]
