# Generated by Django 2.1 on 2020-03-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_products_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
