# Generated by Django 2.1 on 2020-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200317_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='not_available',
            field=models.BooleanField(default=0),
        ),
    ]
