# Generated by Django 2.1 on 2020-03-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_prices_not_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', related_query_name='product_price', to='dashboard.Products'),
        ),
    ]
