# Generated by Django 2.1 on 2020-03-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200328_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapers',
            name='image_element_selector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapers',
            name='price_element_selector',
            field=models.CharField(max_length=100),
        ),
    ]
