# Generated by Django 2.1 on 2020-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200328_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapers',
            name='image_element_selector',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapers',
            name='price_element_selector',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapers',
            name='website_url',
            field=models.CharField(max_length=500),
        ),
    ]
